import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const generatePDF = ({
  userName,
  month,
  year,
  totalIncome,
  totalExpense,
  netSavings,
  transactions,
}) => {
  const doc = new jsPDF();

  // Title
  doc.setFontSize(22);
  doc.setTextColor(37, 99, 235);
  doc.text("FinanceFlow", 105, 20, { align: "center" });

  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.text("Monthly Financial Report", 105, 30, {
    align: "center",
  });

  // User Info
  doc.setFontSize(12);
  doc.text(`Name : ${userName}`, 14, 45);
  doc.text(`Month : ${month} ${year}`, 14, 53);
  doc.text(
    `Generated : ${new Date().toLocaleDateString()}`,
    14,
    61
  );

  // Summary Table
  autoTable(doc, {
    startY: 70,
    head: [["Summary", "Amount"]],
    body: [
  ["Total Income", `Rs. ${Number(totalIncome).toLocaleString()}`],
  ["Total Expense", `Rs. ${Number(totalExpense).toLocaleString()}`],
  ["Net Savings", `Rs. ${Number(netSavings).toLocaleString()}`],
],
    theme: "grid",
    headStyles: {
      fillColor: [37, 99, 235],
    },
  });

  // Transactions Table
  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 12,
    head: [["Date", "Category", "Type", "Amount"]],
    body: transactions.map((item) => [
      new Date(
        item.date || item.createdAt || item.transactionDate
      ).toLocaleDateString(),
      item.category,
      item.type,
      `Rs. ${Number(item.amount).toLocaleString()}`,
    ]),
    theme: "grid",
    headStyles: {
      fillColor: [37, 99, 235],
    },
  });

  // Footer
  doc.setFontSize(10);
  doc.setTextColor(120);
  doc.text(
    "Generated by FinanceFlow",
    105,
    285,
    { align: "center" }
  );

  doc.save(`FinanceFlow-${month}-${year}.pdf`);
};

export default generatePDF;